# Build DSIronPython package using msbuild
name: DSIronPython-VS2022Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: DSIronPython
          repository: DynamoDS/DSIronPython
      - name: Setup nuget
        uses: nuget/setup-nuget@v1.2
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Nuget Restore DSIronPython solution
        run: nuget restore ${{ github.workspace }}\DSIronPython\DSIronPython.sln
      - name: Build DSIronPython with MSBuild
        run: |
          Write-Output "***Continue with the build, Good luck developer!***"
          msbuild ${{ github.workspace }}\DSIronPython\DSIronPython.sln
      - name: Look for package
        run: |
          Write-Output "***Locating iron python package!***"
          if (Test-Path -Path "${{ github.workspace }}\DSIronPython\package_output\DSIronPython\bin\DSIronPython.dll") {
            Write-Output "python node dll exists!"
          } else {
            Write-Error "python node dll was not found!"
          }
      - name: Run test with the dotnet CLI
        run: |
          dotnet test ${{ github.workspace }}\DSIronPython --logger "trx;LogFileName=results.trx" --results-directory ${{ github.workspace }}\DSIronPython\TestResults
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: DSIronPython
          path: ${{ github.workspace }}\DSIronPython\package_output
          retention-days: 7
      - name: Upload test artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: TestResults
          path: ${{ github.workspace }}\DSIronPython\TestResults
          retention-days: 1
